# Generated by Django 4.0.5 on 2022-06-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_video_alter_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
    ]
