# Generated by Django 4.0.5 on 2022-06-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categoria',
            field=models.TextField(null=True, verbose_name='Categoria'),
        ),
    ]
